"""Write docs/data.js (window.DATA = {...}) from the build outputs."""
import json
import sys

from common import DOCUMENTS, FACTORS, KEY_MESSAGES, MERGED, ROOT, load


def main() -> int:
    merged = load(MERGED)
    data = {
        "as_of": merged["as_of"],
        "counts": merged["counts"],
        "factors": FACTORS,
        "documents": load(DOCUMENTS),
        "learnings": merged["learnings"],
        "key_messages": load(KEY_MESSAGES),
    }
    # Escape "</" so report text can never close the <script> tag early.
    payload = json.dumps(data, ensure_ascii=False, indent=1).replace("</", "<\\/")
    out = ROOT / "docs" / "data.js"
    out.write_text(f"// Generated by scripts/build_site.py. Do not edit by hand.\nwindow.DATA = {payload};\n",
                   encoding="utf-8")
    print(f"wrote docs/data.js ({len(data['learnings'])} learnings, {len(data['documents'])} documents)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
